version: 2
jobs:
  docs:
    docker:
      - image: circleci/node:12
    working_directory: ~/elixir_snake
    steps:
      - checkout
      - run: npx prettier --check "**/*.md"
  code:
    docker:
      - image: circleci/elixir:1.9
    working_directory: ~/elixir_snake
    steps:
      - checkout
      - run: mix format --check-formatted
workflows:
  version: 2
  lint:
    jobs:
      - docs
      - code
