name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      
    - name: Setup Elixir
      uses: actions/setup-elixir@1.0.0
      with:
        elixir-version: 1.9.X
        otp-version: 22.X
        
    - name: Run prettier
      run: npx prettier --write "**/*.md"
      
    - name: Run mix format
      run: mix format
    
    - name: Commit
      run: |
        git config --global user.name '${GITHUB_ACTOR}'
        git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
        git add -A
        git commit -m 'Format files' --allow-empty
        git push -u origin HEAD

